/**
 * The sheet the whole site is printed on.
 *
 * Spans the full document and scrolls with it, so the page reads as one
 * continuous sheet. Pure CSS — the noise is generated by SVG filters inlined
 * as data URIs, so there are no image requests and it stays sharp at any DPR.
 */
export function PaperBackground() {
  return (
    <div aria-hidden className="pointer-events-none absolute inset-0 z-0">
      <div className="paper-layer paper-layer--fixed paper-light" />
      <div className="paper-layer paper-mottle" />
      <div className="paper-layer paper-fibre" />
      <div className="paper-layer paper-grain" />
      <div className="paper-layer paper-warmth" />
    </div>
  );
}
